apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-web
  namespace: argocd
  labels:
    name: helm-web
spec:
  generators:
  - list:
      elements:
      - namespace: dev
        url: https://kubernetes.default.svc
      - namespace: stg
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{namespace}}-helm-web'
      labels:
        name: helm-web
    spec:
      project: default
      source:
        helm:
          releaseName: helm-web-ui
          valueFiles:
            - web/values.yaml
            - web/{{namespace}}/values.yaml
        repoURL: https://github.com/devops-systems/argocd-test.git
        targetRevision: HEAD
        path: example2
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
