apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: web
spec:
  generators:
  - list:
      elements:
      - namespace: dev
        url: https://kubernetes.default.svc
      - namespace: stg
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{namespace}}-web'
    spec:
      project: default
      source:
        repoURL: https://github.com/devops-systems/argocd-test.git
        targetRevision: HEAD
        path: example1/web/{{namespace}}
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
