name: GitHubActions

on: 
  push:
    branches: 
      - master

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello Message in Testing
      run : echo "Hello World from Testing job"
      
    - name: List current folder
      run : ls -la
   
    - name: Git clone my repo
      uses: actions/checkout@v1   
  
    - name: List current folder
      run : ls -la
